### ISSUE TITLE
/documentation end-point are not functioning correctly for Admin API on K8s

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/central-ledger#114]
## Scenario
/documentation end-point are not functioning correctly when exposed through the same base URI on Kubernetes deployments

## Issue
On a K8s deployment the Standard API and the Admin API are exposed via the following example URIs through ingress:

Standard API: http://test.api/documentation
Admin API: http://test.api/admin/documentation

When accessing the /documentation end-point for the Admin API, one can see that the source HTML/CSS/JS is actually pointing to the Standard API.

This means that all Swagger capabilities will hit the Standard API instead of the Admin API, and reference the incorrect Swagger depdendencies on the Standard API instead of the Admin API.

## Fix
Configure the Hapi Server on Central-Ledger to correctly configure the base URIs for each of the Standard and Admin APIs.

**Comment by elnyry** [comment]
Story - https://github.com/mojaloop/project/issues/423

**Comment by mdebarros** [comment]
This has been fixed by merging the normal & admin APIs in the Central-Ledger with story: https://github.com/mojaloop/project/issues/600
