### ISSUE TITLE
Fulfil notifications are being sent to both the Payer and Payee FSP

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/central-ledger#123]
## Scenario
Fulfil notifications are being sent to both the Payer and Payee FSP

## Issue
Mojaloop v1 spec only stipulates that the Fulfil notification should go to the Payer FSP

## Fix

1. Confirm that future Mojaloop specs to not send out both notifications to Payer and Payee FSP
2. Remove (Code and Design) 2nd notification to the Payee FSP to align the Mojaloop v1 spec

**Comment by mdebarros** [comment]
@elnyry: Please confirm if we should do the 2nd proposed fix above, or if a future mojaloop spec will be aligned to Fulfil notifications being sent to both FSPs.

**Comment by elnyry** [comment]
I think this is now fixed (configurable to conform to spec, if needed) with mojaloop/project/issues/700
