### ISSUE TITLE
Cannot read property 'findOne' of undefined

### ISSUE THREAD

**Issue by quick20** [mojaloop/central-ledger#193]
Hello,
I am new to this project. I followed the installation process of the central ledger until the server started with npm start. When I try to create a participant with postman, I have the following error: Can not read property 'findOne' of undefined. What is this error due to?

**Comment by NicoDuvenage** [comment]
Hi there quick20,
Thanks for your interest and feedback. We are looking into this issue and will get back to you as soon as possible.
Nico Duvenage

@ksatya77 @bothadeon @rmothilal @mdebarros

**Comment by mdebarros** [comment]
Hi @quick20,

Please confirm what versions you are using.

Specifically the Helm Chart version you are using for your deployments?

**Comment by quick20** [comment]
Hi,
Thank @NicoDuvenage , @mdebarros for your responses.

For now, I have only installed the central ledger by following the resource on [https://github.com/mojaloop/central-ledger/blob/master/Onboarding.md](https://github.com/mojaloop/central-ledger/blob/master/Onboarding.md). However I solved the problem by updating the central-services-database of central ledger with the following command: 
npm install @ mojaloop / central-services-database.
