### ISSUE TITLE
Duplicate notifications kill perf

### ISSUE THREAD

**Issue by bhcrosslake** [mojaloop/central-ledger#2]
It appears as though the central ledger sends duplicate transfer (executed) notifications.
This combines with a Dfsp ledger bug
The connector tries to fulfill the corresponding incoming transfer on the dfsp ledger. However if that transfer has already been fulfilled, it emits an error instead of responding with a 200. Since it doesn’t emit the error in a format the connector understands, it just tries to resubmit the fulfillment.

**Comment by elnyry** [comment]
In the Scope of the FSPs and not the Switch, also the notifications design are now changed (callbacks)
