### ISSUE TITLE
Request for invalid participants returns a non-standard error message

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/central-ledger#282]
Request for invalid participants returns a non-standard error message:
```CURL
curl -X GET \
  http://central-ledger.local/participants/1 \
  -H 'Content-Type: application/json' \
  -H 'cache-control: no-cache'
```

Response HTTP 404 Not found:
```JSON
{
    "id": "NotFoundError",
    "message": "The requested resource could not be found."
}
```

This should return a valid error message in this format:
```JSON
{
  "errorInformation": {
    "errorCode": "string",
    "errorDescription": "string",
    "extensionList": {
      "extension": [
        {
          "key": "string",
          "value": "string"
        }
      ]
    }
  }
}
```

**Comment by ggrg** [comment]
Hi @mdebarros, @elnyry, there is more than the reported endpoint:
```
GET http://{{CL}}/participant
{
    "id": "NotFoundError",
    "message": "Not Found"
}
GET http://{{CL}}/participants/{{payerFsp}}1
{
    "id": "NotFoundError",
    "message": "The requested resource could not be found."
}
GET http://{{CL}}/participants/{{payerFsp}}1/endpoints
{
    "id": "BadRequestError",
    "message": "Participant does not exist"
}
GET http://{{CL}}/participants/{{payerFsp}}1/limits
{
    "id": "BadRequestError",
    "message": "Participant does not exist"
}
GET http://{{CL}}/participants/{{payerFsp}}1/positions
{
    "id": "BadRequestError",
    "message": "Participant does not exist"
}
http://{{CL}}/participants/{{payerFsp}}1/accounts
{
    "id": "BadRequestError",
    "message": "Participant does not exist"
}
http://{{CL}}/participants/Hub1/accounts?currency=USD
{
    "id": "BadRequestError",
    "message": "Participant does not exist"
}

**Comment by ggrg** [comment]
After looking at the settlements pattern, I can see:
```
GET http://{{CS}}/settlementWindows/5
{
    "statusCode": 400,
    "error": "Bad Request",
    "message": {
        "errorInformation": {
            "errorDescription": "2001: Window 5 does NOT EXIST'"
        }
    }
}
GET http://{{CS}}/settlementWindows?state=CLOSED&participantId=3
{
    "statusCode": 404,
    "error": "Not Found",
    "message": {
        "errorInformation": {
            "errorDescription": "settlementWindow by filters: {state:CLOSED,participantId:3} not found"
        }
    }
}
POST http://{{CS}}/settlements
{
    "statusCode": 400,
    "error": "Bad Request",
    "message": {
        "errorInformation": {
            "errorDescription": "At least one settlement window does not exist"
        }
    }
}
GET http://{{CS}}/settlements/7
{
    "statusCode": 404,
    "error": "Not Found",
    "message": {
        "errorInformation": {
            "errorDescription": "2001 TODO Settlement not found"
        }
    }
}
and so on ...
```

**Comment by ggrg** [comment]
The reason for this inconsistency is I guess, these are admin endpoints and are not covered by the API Specification 1.0. If this is to be changed, then we certainly need more generic approach:
1. Central-ledger uses errors defined at `/src/errors` and at `@mojaloop/central-services-shared/src/errors`
2. Central-settlement holds error definitions inline and as you may see above the returned response payload has slightly different payload, than the defined at the top. Also having some error texts containing `TODO` explains we created technical debt in the past (which wasn't that important back then).

Having all this described, I would suggest we close this and create a new feature story, which better describes the way we define (probably extending central-services-shared to hold the full range of errorCodes defined by the spec), handle and respond to admin related errors.

Please, comment.

**Comment by elnyry** [comment]
Thanks @ggrg . The admin endpoints though not covered by the API Spec, the team and DA decided to follow a uniform format for the error message (ML API, Settlements, Admin), so it needs to be uniform.

Thanks for documenting the additional use cases. It will help in creating a new story as you mentioned.

**Comment by mdebarros** [comment]
> The reason for this inconsistency is I guess, these are admin endpoints and are not covered by the API Specification 1.0. If this is to be changed, then we certainly need more generic approach:
> 
> 1. Central-ledger uses errors defined at `/src/errors` and at `@mojaloop/central-services-shared/src/errors`
> 2. Central-settlement holds error definitions inline and as you may see above the returned response payload has slightly different payload, than the defined at the top. Also having some error texts containing `TODO` explains we created technical debt in the past (which wasn't that important back then).
> 
> Having all this described, I would suggest we close this and create a new feature story, which better describes the way we define (probably extending central-services-shared to hold the full range of errorCodes defined by the spec), handle and respond to admin related errors.
> 
> Please, comment.

Totally agree with you on the consistency. The reason I opened this as a bug is that it does NOT follow the standard Mojaloop error messages. The error codes may not match the API, but at least the structure should at the very least.

**Comment by elnyry** [comment]
Covered in mojaloop/project/issues/561
