### ISSUE TITLE
Readme.md and Onboarding.me does not indicate that the sidecar should be disabled for local development

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/central-ledger#38]
Readme.md and Onboarding.me does not indicate that the sidecar should be disabled when running Central-Ledger locally. It only describes the steps needs to start the PostgreSQL DB as a pre-requisite in the onboarding guide.

It should also include information on how to disable the sidecar for local development. Specifically updating the config/default.json file from:

``` JSON
  "SIDECAR": {
    "DISABLED": false,
    "HOST": "localhost",
    "PORT": 5678,
    "CONNECT_TIMEOUT": 45000,
    "RECONNECT_INTERVAL": 5000
  },
```

The change being `"DISABLED": false` to `"DISABLED": true` as follows:

``` JSON
  "SIDECAR": {
    "DISABLED": true,
    "HOST": "localhost",
    "PORT": 5678,
    "CONNECT_TIMEOUT": 45000,
    "RECONNECT_INTERVAL": 5000
  },
```

**Comment by elnyry** [comment]
Closing this as this step exists now in [Onboarding.md](https://github.com/mojaloop/central-ledger/blob/master/Onboarding.md):
"disable SIDECAR in config/default.json temporary by setting "SIDECAR": { "DISABLED": "true", ... "
