### ISSUE TITLE
npm start does not seem to be working in MinGW

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/central-ledger#40]
@georgi-sgbg was unable to start Central-Ledger using MinGW in a Windows environment.

1. Has anybody started the Central-Ledger API using MacOS/Ubuntu?
2. Has anybody been able to re-produce the issue in a Windows MinGW environment?

**Comment by georgi-sgbg** [comment]
I succeeded starting Central-Ledger in Windows after adding the following to package.json:

"scripts": {
    "win": "run-p win:api win:admin",
    "win:api": "SET CLEDG_HOSTNAME=http://localhost:3000&&node src/api/index.js",
    "win:admin": "SET CLEDG_ADMIN_KEY=admin&&SET CLEDG_ADMIN_SECRET=admin&&SET CLEDG_HOSTNAME=http://localhost:3001&&node src/admin/index.js"
}

and running:
npm run win

**Comment by elnyry** [comment]
Closing this based on Georgi's comment above. Please re-open if repro-ed again
