### ISSUE TITLE
Transfer API SVC Version Error - Cannot bootstrap authentication service

### ISSUE THREAD

**Issue by ZweHMyat** [mojaloop/central-ledger#963]
When I start the integration test with "npm run test:integration", authentication svc cannot bootstrap error occurs. I was informed this happens due to the incompatible versions between transfer svc and authN service. The exact error log is as follow:

(transfers-bc transfers-api-svc v0.0.1) (AuthorizationClient) [] error: AxiosError: Request failed with status code 400 meta: "Could not bootstrap privileges to Authentication Service"

As we can see in the log, transfer-api-svc starting with v0.0.1 even though when I run the service with "npm run start:transfers-api-svc" the version appears to be v0.2.2, which matches the version in the package.json, and it runs without any problems. I don't understand how the integration test got the v0.0.1.

Please kindly help with the issue. Thank you.

[Integration test](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaFU3IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--94cddaa7cba41049b544d35b9d83a771fc51e1c7/Screenshot%202023-08-25%20162354.png)

[Normal service start](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaGc3IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--5db4ef3c0b57c84788041c8f183aa21b05b68341/Screenshot%202023-08-25%20162458.png)

**Comment by elnyry-sam-k** [comment]
@ZweHMyat , from the snapshots and description, are you sure this is the right place for this bug / issue?

Ideally, bug should be logged here, following the template here: https://github.com/mojaloop/project/issues/new?assignees=&labels=bug&projects=&template=bug_report.md&title= , but in any case, this seems to belong either in https://github.com/mojaloop/transfers-bc or a related repo

**Comment by elnyry-sam-k** [comment]
Closing here as there's an issue in project repo now..

**Comment by ZweHMyat** [comment]
Hi Sam,

Thank you for closing it. I forgot to change the default project and I couldn't close the ticket afterwards as I didn't have access.
________________________________
